version: '3.9'
services:
  rates-postgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rateservicedb
    ports:
      - '5432:5432'
    volumes:
      - ./postgreSQL/init-db.sql:/docker-entrypoint-initdb.d/init.sql