spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rateservicedb
    username: user
    password: password

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    org.springframework.r2dbc.connection: TRACE