CREATE TABLE IF NOT EXISTS PRICES
(
    BRAND_ID   VARCHAR(10)    NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRICE_LIST VARCHAR(10)    NOT NULL,
    PRODUCT_ID VARCHAR(10)    NOT NULL,
    PRIORITY   VARCHAR(10)    NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       VARCHAR(3)     NOT NULL,
    PRIMARY KEY (BRAND_ID, START_DATE, PRICE_LIST, PRODUCT_ID)
);